config/routes.rb
Rails.application.routes.draw do
  root to: 'chats#index'
  resources :companies do
    resources :shops do
      resources :employees
      resources :shop_slots, except: [:index, :show]
      get :index_appointment
      put :change_status
    end
  end

  resources :users do
    resources :appointments, except: [:index] do
      resources :notes, only: [:new, :create]
    end
    put :change_status
    put :block_user
  end

  resources :sessions

  resources :chats

  get 'new_contact_message', to: 'contacts#new', as: 'new_contact_message'
  post 'create_contact_message', to: 'contacts#create', as: 'create_contact_message'

  get 'users_list', to: 'users#index_admin', as: 'users_list'
  get 'signup',  to: 'users#new', as: 'signup'
  get 'signin',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'recoverPassword', to: 'users#recoverPassword'

  scope module: 'api', path: 'api' do
    resources :companies, only: [:index], as: 'api_companies'

    get 'companies/:id/shops', to: 'shops#index', as: 'api_company_shops'
    get 'companies/shops', to: 'shops#all_shops', as: 'api_companies_shops'

    get 'shops/:id/appointments', to: 'appointments#index', as: 'api_appointments_index'
    get 'shops/:id/appointments/date/:date', to: 'appointments#date', as: 'api_appointments_index_date'

    get 'shops/:id/shop_slots', to: 'shop_slots#index'

    post 'create_contact_message', to: 'contacts#create', as: 'api_contacts_create'
    get 'index_contact_message', to: 'contacts#index', as: 'api_contacts'
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  belongs_to :address, dependent: :delete
  belongs_to :company
  has_many :employees
  has_many :shop_slots
  has_many :appointments

  accepts_nested_attributes_for :address

  validates :name, presence: true, length: { maximum: 20 }

  validates :email, presence: true,
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def fully_scheduled?
    if shop_slots.count == 7
      true
    else
      false
    end
  end
end

app/controllers/api/shops_controller.rb
module Api
  class ShopsController < ApplicationController
    def index
      @company = Company.find(params[:id])
      @shops = Shop.all.where(company_id: params[:id])
      render json: @shops
    end

    def all_shops
      @shops = Shop.all
      render json: @shops
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  load_and_authorize_resource :company
  load_and_authorize_resource :shop, through: :company

  def new
    @address = @shop.build_address
  end

  def create
    @shop = Shop.new(shop_params.merge(address_params).merge(company_id: @company.id))
    if @shop.save
      flash[:success] = 'The shop has been created!'
      redirect_to company_shop_path(@company, @shop)
    else
      flash[:failure] = "The couldn't be created!"
      render 'new'
    end
  end

  def show
    @slots = @shop.shop_slots.order('day ASC')
    return redirect_to company_shops_path if @shop.blank?
  end

  def edit
    return redirect_to company_shops_path if @shop.blank?
  end

  def update
    if @shop.update(shop_params.merge(address_params))
      flash[:success] = 'The shop has been updated!'
      return redirect_to company_shop_path(@company, @shop)
    else
      flash[:failure] = "The shop couldn't be updated!"
      render 'edit'
    end
  end

  def destroy
    @shop.destroy
    flash[:success] = 'The shop has been deleted!'
    redirect_to company_shops_path(@company)
  end

  def index
  end

  def index_appointment
    @company = Company.find(params[:company_id])
    authorize! :show, @company
    @shop = Shop.find(params[:shop_id])
    authorize! :show, @shop
    @appointments = Appointment.where(shop_id: @shop.id)
  end

  def change_status
    @appointment = Appointment.find(params[:appointment])
    @company = Company.find(params[:company_id])
    authorize! :show, @company
    @shop = Shop.find(params[:shop_id])
    authorize! :show, @shop
    @appointment = Appointment.find(params[:appointment])
    case params[:status]
    when 'ready_for_pickup'
      if @appointment.ready_for_pickup!
        flash[:success] = 'The appointment has been updated to ready for pickup!'
        return redirect_to company_shop_index_appointment_path(@company, @shop)
      else
        flash[:danger] = "The appointment couldn't be updated!"
      end
    when 'finished'
      if @appointment.finished!
        flash[:success] = 'The appointment has been finalized!'
        return redirect_to company_shop_index_appointment_path(@company, @shop)
      else
        flash[:danger] = "The appointment couldn't be updated!"
      end
    else
      flash[:danger] = "The appointment couldn't be updated!"
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :email, :active)
  end

  def address_params
    params.require(:shop).permit(address_attributes: [:short_address, :full_address, :city, :zipcode, :country])
  end
end

app/views/shops/edit.html.erb
<h1>Edit <%= @shop.name %></h1>

<div class="form">
  <%= form_for [@company, @shop] do |shop_form | %>
    <%= render 'shared/error_messages', object: shop_form.object %>
    <%= shop_form.label :name %>
    <%= shop_form.text_field :name %>

    <%= shop_form.label :email %>
    <%= shop_form.text_field :email %>
    <div id="active">
      <div> <%= shop_form.label :active %> </div>
      <div> <%= shop_form.check_box :active %></div>
    </div>
    <%= shop_form.fields_for :address do |address_form| %>
      <%= address_form.label :short_address %>
      <%= address_form.text_field :short_address %>

      <%= address_form.label :full_address %>
      <%= address_form.text_field :full_address %>

      <%= address_form.label :city %>
      <%= address_form.text_field :city %>

      <%= address_form.label :zipcode %>
      <%= address_form.text_field :zipcode %>

      <%= address_form.label :country %>
      <%= address_form.text_field :country %>
    <% end %>
    <div class="more">
      <div class="button save"><%= shop_form.submit "Save changes", class: "btn btn-primary" %></div>
      <div class="button back"><%= link_to "Back", company_shop_path(@company, @shop), class: "btn btn-primary"  %></div>
    </div>
  <% end %>
</div>

app/views/shops/index.html.erb
<% if @shops.present? %>
  <h1>All the shops that belong to the company: <%= @company.name %></h1>
  <div class="show">
    <ul>
      <% @shops.each do |shop| %>
        <li>
          <%= link_to shop.name, company_shop_path(@company, shop) %>
        </li>
      <% end %>
    </ul>
    <div class="showbtn">
      <%= link_to "Create a new shop" , new_company_shop_path, class: "btn btn-primary" %>
      <%= link_to "Back to the company", company_path(@company), class: "btn btn-primary" %>
    </div>
  </div>
<% else %>
  <h1>
    This company has no shops
  </h1>
<% end %>

app/views/shops/index_appointment.html.erb
<h2>
  All the appointments that belong to <%= @shop.name %>
</h2>

<div class="show">
  <ul>
    <% @appointments.each do |appointment| %>
      <li>
        Appointment from <%= appointment.date %>,
        containing <%= pluralize(appointment.item_number, 'item') %>,
        has the status of <b><%= appointment.status.humanize -%></b>.
        <% if appointment.booked? %>
          <%= link_to "Change to Ready for pickup",
                       company_shop_change_status_path(@company, @shop, appointment: appointment.id, status: 'ready_for_pickup'),
                       method: :put,
                       class: "btn btn-primary",
                       data: { confirm: "Are you sure you want to change the status?" } %>
        <% elsif appointment.ready_for_pickup?  %>
          <%= link_to "Change to finished ",
                       company_shop_change_status_path(@company, @shop, appointment: appointment.id, status: 'finished'),
                       method: :put,
                       class: "btn btn-primary",
                       data: { confirm: "Are you sure you want to change the status?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="showbtn">
    <%= link_to "Back to the shop", company_shop_path(@company, @shop), class: "btn btn-primary" %>
  </div>
</div>

app/views/shops/new.html.erb
<h1>Create a new shop. Input information for a new shop</h1>

<div class="form">
  <%= form_for [@company, @shop],
                url:company_shops_path(@company),
                method: :post  do |shop_form | %>
    <%= render 'shared/error_messages', object: shop_form.object %>
      <%= shop_form.label :name %>
      <%= shop_form.text_field :name %>

      <%= shop_form.label :email %>
      <%= shop_form.text_field :email %>

      <%= shop_form.fields_for :address do |address_form| %>
        <%= address_form.label :short_address %>
        <%= address_form.text_field :short_address %>

        <%= address_form.label :full_address %>
        <%= address_form.text_field :full_address %>

        <%= address_form.label :city %>
        <%= address_form.text_field :city %>

        <%= address_form.label :zipcode %>
        <%= address_form.text_field :zipcode %>

        <%= address_form.label :country %>
        <%= address_form.text_field :country %>
      <% end %>
    <div class="more">
      <div class="button save"><%= shop_form.submit "Create a new shop", class: "btn btn-primary" %></div>
      <div class="button back"><%= link_to "Back", company_shops_path(@company), class: "btn btn-primary"  %></div>
    </div>
  <% end %>
</div>

app/views/shops/show.html.erb
<h2>
  Information about <b><%= @shop.name %></b> which belongs to <b><%= @company.name %></b>
</h2>

 <div class="show">
   <ul>
    <li>Shop name:<%= @shop.name %></li>
    <li>Shop email:<%= @shop.email %></li>
    <%= render 'shared/active_or_no', active: @shop.active %>
    <li>Short address:<%= @shop.address.short_address %></li>
    <li>Long address:<%= @shop.address.full_address %></li>
    <li>City:<%= @shop.address.city %></li>
    <li>Zipcode:<%= @shop.address.zipcode %></li>
    <li>Country:<%= @shop.address.country %></li>
  </ul>
  <h2>
    Working hours and avalilable slots:
  </h2>
  <ul>
    <% @slots.each do |shop_slot| %>
      <li>
        <%= shop_slot.week_day %> working hours:
        </br>
        Shop opens at <%= shop_slot.open_hour.strftime("%H:%M") %> and closes at <%= shop_slot.close_hour.strftime("%H:%M") %>.
        Maximum slots available: <%= shop_slot.max_appointments %>
        <div class=""><%= link_to "Edit #{shop_slot.week_day} slot", edit_company_shop_shop_slot_path(@company, @shop, shop_slot) , class: "btn btn-primary" %></div>
      </li>
    <% end %>
  </ul>

  <div class="showbtn">

    <%= link_to "Edit shop", edit_company_shop_path(@company, @shop) , class: "btn btn-primary", id: "test" %>
    <%= link_to "Add employee", new_company_shop_employee_path(@company, @shop), class: "btn btn-primary" %>
    <%= link_to "Show all employees", company_shop_employees_path(@company, @shop), class: "btn btn-primary" %>
    <%= link_to "Show all appointments", company_shop_index_appointment_path(@company, @shop), class: "btn btn-primary" %>
    <%= link_to "Add shop slots", new_company_shop_shop_slot_path(@company, @shop) , class: "btn btn-primary" unless @shop.fully_scheduled? %>
    <%= link_to "Delete", company_shop_path(@company, @shop), data: { confirm: 'Are you sure you want to delete the shop?' }, :method => :delete, class: 'btn btn-primary'%>
    <%= link_to "Back to shops" , company_shops_path, class: "btn btn-primary" %>
  </div>
</div>