config/routes.rb
Rails.application.routes.draw do
  root to: 'chats#index'
  resources :companies do
    resources :shops do
      resources :employees
      resources :shop_slots, except: [:index, :show]
      get :index_appointment
      put :change_status
    end
  end

  resources :users do
    resources :appointments, except: [:index] do
      resources :notes, only: [:new, :create]
    end
    put :change_status
    put :block_user
  end

  resources :sessions

  resources :chats

  get 'new_contact_message', to: 'contacts#new', as: 'new_contact_message'
  post 'create_contact_message', to: 'contacts#create', as: 'create_contact_message'

  get 'users_list', to: 'users#index_admin', as: 'users_list'
  get 'signup',  to: 'users#new', as: 'signup'
  get 'signin',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'recoverPassword', to: 'users#recoverPassword'

  scope module: 'api', path: 'api' do
    resources :companies, only: [:index], as: 'api_companies'

    get 'companies/:id/shops', to: 'shops#index', as: 'api_company_shops'
    get 'companies/shops', to: 'shops#all_shops', as: 'api_companies_shops'

    get 'shops/:id/appointments', to: 'appointments#index', as: 'api_appointments_index'
    get 'shops/:id/appointments/date/:date', to: 'appointments#date', as: 'api_appointments_index_date'

    get 'shops/:id/shop_slots', to: 'shop_slots#index'

    post 'create_contact_message', to: 'contacts#create', as: 'api_contacts_create'
    get 'index_contact_message', to: 'contacts#index', as: 'api_contacts'
  end
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  belongs_to :address, dependent: :delete
  has_one :employee, inverse_of: :user
  has_many :appointments
  has_many :notes

  has_secure_password
  accepts_nested_attributes_for :address

  validates :name, presence: true, length: { maximum: 20 }
  validates :username, presence: true, length: { maximum: 20 }
  validates :password, presence: true, length: { minimum: 6 }

  validates :email, presence: true,
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def new
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new
      @address = @user.build_address
    end
  end

  def create
    @user = User.new(user_params.merge(address_params))
    if @user.save
      flash[:success] = 'The user has been created!'
      AppointmentMailer.user_creation_confirmation_email(@user).deliver_now
      redirect_to login_path
    else
      flash[:danger] = "The user couldn't be created!"
      render 'new'
    end
  end

  def show
  end

  def edit
    @user = User.find_by(id: params[:id])
    return redirect_to users_path if @user.blank?
  end

  def update
    @user = User.find_by(id: params[:id])
    if current_user.admin? && update_admin_user_params
      flash[:success] = "The user #{@user.name} has been updated!"
      redirect_to user_path(@user)
    elsif @user.update(user_params.merge(address_params))
      flash[:success] = 'The user has been updated!'
      redirect_to user_path(@user)
    else
      flash[:danger] = "The user couldn't be updated!"
      render 'edit'
    end
  end

  def destroy
    if @user == current_user
      flash[:danger] = 'You cannot delete yourself!'
      redirect_to user_path(@user)
    else
      @user.destroy
      flash[:success] = 'The user has been deleted!'
      redirect_to users_path
    end
  end

  def index
  end

  def recoverPassword
  end

  def index_admin
    authorize! :block_user, @user
    @users = User.order(created_at: :asc).all
  end

  def change_status
    @user = User.find(params[:user])
    authorize! :change_status, @user
    if !@user.active
      @user.update_attribute(:active, true)
      AppointmentMailer.user_activation_email(@user).deliver_now
      flash[:success] = 'The user is now active!'
      redirect_to users_list_path
    else
      flash[:danger] = 'The user cannot be updated'
    end
  end

  def block_user
    @user = User.find(params[:user])
    authorize! :block_user, @user
    if !@user.blocked
      if @user.update_attribute(:blocked, true)
        AppointmentMailer.user_block_email(@user).deliver_now
        flash[:success] = 'The user has been banned!'
        redirect_to users_list_path
      else
        flash[:danger] = 'The user cannot be updated'
      end
    elsif @user.blocked
      if @user.update_attribute(:blocked, false)
        flash[:success] = 'The ban on the user has been lifted!'
        redirect_to users_list_path
      else
        flash[:danger] = 'The user cannot be updated'
      end
    else
      flash[:danger] = "The action couldn't be done"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password,
                                 :password_confirmation, :admin,
                                 :active, :blocked)
  end

  def update_admin_user_params
    params.require(:user).permit(:name, :username, :email)
    params[:user].each do |key, value|
      if key != "address_attributes"
        @user.update_attribute(key, value)
      end
    end
    params[:user][:address_attributes].each do |key_addr, value_addr|
      @user.address.update_attribute(key_addr, value_addr)
    end
  end

  def address_params
    params.require(:user).permit(address_attributes: [:short_address,
                   :full_address, :city, :zipcode, :country])
  end
end

app/views/users/edit.html.erb
<h2 align="center">Edit your profile!</h2>

<div class="row justify-content-center align-items-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |user_form| %>
      <%= render 'shared/error_messages', object: user_form.object %>

      <%= user_form.label :name, :error_html => { :class => 'cant_be_blank'}  %>
      <%= user_form.text_field :name %>

      <%= user_form.label :username %>
      <%= user_form.text_field :username %>

      <%= user_form.label :email %>
      <%= user_form.text_field :email %>

      <% if !current_user.admin? %>

        <%= user_form.label :password %>
        <%= user_form.password_field :password %>

        <%= user_form.label :password_confirmation %>
        <%= user_form.password_field :password_confirmation %>

      <% end %>

      <div id="active">
        <% if @user.admin %>
          <div><%= user_form.label :admin %></div>
          <div><%= user_form.check_box :admin %></div>
        <% end %>
      </div>
       <%= user_form.fields_for :address do |address_form| %>
         <%= address_form.label :short_address %>
         <%= address_form.text_field :short_address %>

         <%= address_form.label :full_address %>
         <%= address_form.text_field :full_address %>

         <%= address_form.label :city %>
         <%= address_form.text_field :city %>

         <%= address_form.label :zipcode %>
         <%= address_form.text_field :zipcode %>

         <%= address_form.label :country %>
         <%= address_form.text_field :country %>
      <% end %>
      <div class="more">
        <div class="button save"><%= user_form.submit "Save profile", class: "btn btn-primary" %></div>
        <div class="button back"><%= link_to "Back", users_path, class: "btn btn-primary"  %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>
  Showing all users
</h1>
<div class="show">
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
  </ul>
  Logged in as <%= current_user.email %>.
  <%= link_to 'Log Out', logout_path %>
</div>

app/views/users/index_admin.html.erb
<h2>
  Existing users
</h2>

<div class="show">
  <ul>
    <% @users.each do |user| %>
      <li>
        <table class="user-list">
          <tr>
            <th>Username</th>
            <th>Status</th>
            <th>Blocked</th>
          </tr>
          <tr>
            <td><%= user.username %></td>
            <td>
              <span><%= user.active? ? "Active" : "Inactive" %></span>
              <br>
              <% if !user.active %>
                <%= link_to "Activate",
                             user_change_status_path(user, user: user.id, status: 'Active'),
                             method: :put,
                             class: "btn btn-primary",
                             data: { confirm: "Are you sure you want to activate the user?" } %>
              <% end %>
            </td>
            <td>
              <span><%= user.blocked? ? "Blocked" : "Not blocked" %></span>
              <br>
              <% if user.id != current_user.id %>
              <% if user.blocked == false %>
                <%= link_to "Block the user",
                             user_block_user_path(user, user: user.id, status: 'Block user'),
                             method: :put,
                             class: "btn btn-primary",
                             data: { confirm: "Are you sure you want to block the user?" } %>
              <% else %>
                <%= link_to "Lift the ban",
                             user_block_user_path(user, user: user.id, status: 'Unblock user'),
                             method: :put,
                             class: "btn btn-primary",
                             data: { confirm: "Are you sure you want to lift the ban?" } %>
              <% end %>
              <% end %>
            </td>
          </tr>
        </table>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<h1>
  Sign up
</h1>

<div class="form">
    <%= form_for(@user) do |user_form| %>
      <%= render 'shared/error_messages', object: user_form.object %>

      <%= user_form.label :username %>
      <%= user_form.text_field :username %>

      <%= user_form.label :name %>
      <%= user_form.text_field :name %>

      <%= user_form.label :password %>
      <%= user_form.password_field :password %>

      <%= user_form.label :password_confirmation %>
      <%= user_form.password_field :password_confirmation %>

      <%= user_form.label :email %>
      <%= user_form.text_field :email %>

       <%= user_form.fields_for :address do |address_form| %>
         <%= address_form.label :short_address %>
         <%= address_form.text_field :short_address %>

         <%= address_form.label :full_address %>
         <%= address_form.text_field :full_address %>

         <%= address_form.label :city %>
         <%= address_form.text_field :city %>

         <%= address_form.label :zipcode %>
         <%= address_form.text_field :zipcode %>

         <%= address_form.label :country %>
         <%= address_form.text_field :country %>
      <% end %>
      <div class="more">
        <div class="button save"><%= user_form.submit "Sign up", class: "btn btn-primary" %></div>
        <div class="button back"><%= link_to "Back", root_path, class: "btn btn-primary"  %></div>
      </div>
    <% end %>
</div>

app/views/users/recoverPassword.erb
<h1>Recover password</h1>
<div>
  <%= link_to "Back to sign in", new_session_path, class: "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<h2>
  This is your profile!
</h2>

<div class="show">
  <ul>
    <li>Name: <%= @user.name %></li>
    <li>Email: <%= @user.email %></li>
    <li>Username: <%= @user.username %></li>
    <% if @user.admin %>
      <li>Is admin? <%= @user.admin %></li>
    <% end %>
    <li>Short address: <%= @user.address.short_address %></li>
    <li>Full address: <%= @user.address.full_address %></li>
    <li>City: <%= @user.address.city %></li>
    <li>Zipcode: <%= @user.address.zipcode %></li>
    <li>Country: <%= @user.address.country %></li>
  </ul>

  <h3>
    User appointments:
  </h3>

  <ol>
    <% @user.appointments.each do |appointment| %>
      <li>About appointment from <%= appointment.date %>, containing <%= pluralize(appointment.item_number, 'item') %>, with status of <%= appointment.status -%>.
        </br> Link to: <%= link_to "appointment", user_appointment_path(@user, appointment) %></li>
    <% end %>
  </ol>
<div class="showbtn">
  <%= link_to "Edit profile", edit_user_path(@user) , class: "btn btn-primary" %>
  <% if current_user.admin? && !@user.admin? %>
    <%= link_to "Delete user", user_path(@user), method: :delete , class: "btn btn-primary" , data: { confirm: "Are you sure you want to delete the user?" } %>
  <% end %>
  <%= link_to "Create a new appointment", new_user_appointment_path(@user) , class: "btn btn-primary"%>
  <%= link_to "Back to users page" , users_path, class: "btn btn-primary" %>
  <%= link_to 'Log Out', logout_path, class: "btn btn-primary" %>
</div>
</div>