config/routes.rb
Rails.application.routes.draw do
  root to: 'chats#index'
  resources :companies do
    resources :shops do
      resources :employees
      resources :shop_slots, except: [:index, :show]
      get :index_appointment
      put :change_status
    end
  end

  resources :users do
    resources :appointments, except: [:index] do
      resources :notes, only: [:new, :create]
    end
    put :change_status
    put :block_user
  end

  resources :sessions

  resources :chats

  get 'new_contact_message', to: 'contacts#new', as: 'new_contact_message'
  post 'create_contact_message', to: 'contacts#create', as: 'create_contact_message'

  get 'users_list', to: 'users#index_admin', as: 'users_list'
  get 'signup',  to: 'users#new', as: 'signup'
  get 'signin',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'recoverPassword', to: 'users#recoverPassword'

  scope module: 'api', path: 'api' do
    resources :companies, only: [:index], as: 'api_companies'

    get 'companies/:id/shops', to: 'shops#index', as: 'api_company_shops'
    get 'companies/shops', to: 'shops#all_shops', as: 'api_companies_shops'

    get 'shops/:id/appointments', to: 'appointments#index', as: 'api_appointments_index'
    get 'shops/:id/appointments/date/:date', to: 'appointments#date', as: 'api_appointments_index_date'

    get 'shops/:id/shop_slots', to: 'shop_slots#index'

    post 'create_contact_message', to: 'contacts#create', as: 'api_contacts_create'
    get 'index_contact_message', to: 'contacts#index', as: 'api_contacts'
  end
end

app/models/company.rb
class Company < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :shops
  has_many :shop_slots, through: :shop
  has_many :employees

  validates :name, presence: true, length: { maximum: 20 },
                   uniqueness: true

  validates :email, presence: true,
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/api/companies_controller.rb
module Api
  class CompaniesController < ApplicationController
    def index
      @companies = Company.all
      render json: @companies
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource
  def new
  end

  def create
    if @company.save
      flash[:success] = 'The company has been created!'
      redirect_to @company
    else
      flash[:failure] = "The company couldn't be created!"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @company.update_attributes(company_params)
      flash[:success] = 'The company has been updated!'
      redirect_to @company
    else
      flash[:failure] = "The company couldn't be updated!"
      render 'edit'
    end
  end

  def destroy
    @company.destroy
    flash[:success] = 'The company has been deleted!'
    redirect_to companies_path
  end

  def index
  end

  private

  def company_params
    params.require(:company).permit(:name, :email, :active)
  end
end

app/views/companies/edit.html.erb
<h2 align="center">
  Update your company profile
</h2>

<div class="form">
  <%= form_for(@company) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    <div id="active">
      <div><%= f.label :active %></div>
      <div><%= f.check_box :active %></div>
    </div>
    <div class="more">
      <div class="button save"><%= f.submit "Save changes", class: "btn btn-primary" %></div>
      <div class="button back"><%= link_to "Back", @company, class: "btn btn-primary"  %></div>
    </div>
  <% end %>
</div>

app/views/companies/index.html.erb
<h1>All the registered companies</h1>

<div class="show">
  <ul>
    <% @companies.each do |company| %>
      <li>
        <%= link_to company.name, company_path(company) %>
      </li>
    <% end %>
      <% if can? :create, @company %>
        <div class="showbtn">
          <%= link_to "Create a new company" , new_company_path, class: "btn btn-primary" %>
        </div>
      <% end %>
  </ul>
</div>

app/views/companies/new.html.erb
<h1>Create a new company</h1>

<div class="form">
  <%= form_for(@company) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    <div class="more">
      <div class="button save"><%= f.submit "Create a new company", class: "btn btn-primary" %></div>
      <div class="button back"><%= link_to "Back", companies_path, class: "btn btn-primary"  %></div>
    </div>
  <% end %>
</div>

app/views/companies/show.html.erb
<h2>
  Information about <%= @company.name %>
</h2>
<div class="show">
  <ul>
    <li>Name: <%= @company.name %></li>
    <li>Email: <%= @company.email %></li>
    <%= render 'shared/active_or_no', active: @company.active  %>
  </ul>
  <div class="showbtn">
    <%= link_to "Edit the company profile",  edit_company_path(@company), class: "btn btn-primary" %>
    <%= link_to "Delete the company", @company, method: :delete, class: "btn btn-primary", data: { confirm: "Are you sure you want to delete the company?" } %>
    <%= link_to "Create a new shop", new_company_shop_path(@company), class: "btn btn-primary" %>
    <%= link_to "Show all shops", company_shops_path(@company) , class: "btn btn-primary"%>
    <%= link_to "Back", companies_path , class: "btn btn-primary"%>
  </div>
</div>