config/routes.rb
Rails.application.routes.draw do
  root to: 'chats#index'
  resources :companies do
    resources :shops do
      resources :employees
      resources :shop_slots, except: [:index, :show]
      get :index_appointment
      put :change_status
    end
  end

  resources :users do
    resources :appointments, except: [:index] do
      resources :notes, only: [:new, :create]
    end
    put :change_status
    put :block_user
  end

  resources :sessions

  resources :chats

  get 'new_contact_message', to: 'contacts#new', as: 'new_contact_message'
  post 'create_contact_message', to: 'contacts#create', as: 'create_contact_message'

  get 'users_list', to: 'users#index_admin', as: 'users_list'
  get 'signup',  to: 'users#new', as: 'signup'
  get 'signin',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'recoverPassword', to: 'users#recoverPassword'

  scope module: 'api', path: 'api' do
    resources :companies, only: [:index], as: 'api_companies'

    get 'companies/:id/shops', to: 'shops#index', as: 'api_company_shops'
    get 'companies/shops', to: 'shops#all_shops', as: 'api_companies_shops'

    get 'shops/:id/appointments', to: 'appointments#index', as: 'api_appointments_index'
    get 'shops/:id/appointments/date/:date', to: 'appointments#date', as: 'api_appointments_index_date'

    get 'shops/:id/shop_slots', to: 'shop_slots#index'

    post 'create_contact_message', to: 'contacts#create', as: 'api_contacts_create'
    get 'index_contact_message', to: 'contacts#index', as: 'api_contacts'
  end
end

app/views/layouts/_footer.html.erb
<footer class="navbar-bottom navbar-sticky-bottom navbar-expand-md bg-dark">
  <nav>
    <ul>
      <li><%= link_to "Contact Us", new_contact_message_url, id: "user" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-top navbar-sticky-top navbar-expand-md bg-dark">
  <div class="navbar-inner">
    <div class="cont">
      <%= link_to "Bike shop", root_url, id: "logo" %>
        <div class="navbar-nav ml-auto">
          <% if current_user %>
            <%= link_to "User List", users_list_path, id: 'user' %>
            <%= link_to "#{current_user.username}", user_path(current_user), id: "current-user" %>
          <% else %>
            <%= link_to "Sign in", new_session_path, id: "current-user" %>
          <% end %>
        </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/appointment_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
     h1 {
       padding-top: 15px;
       font-size: 3em;
       letter-spacing: -2px;
       margin-bottom: 30px;
       text-align: center;
     }

     ul {
       list-style-type: none;
       margin: 0;
       padding: 0;
       text-decoration: none;
       text-align: center;
     }

     li {
       font: 200 20px/1.5 Helvetica, Verdana, sans-serif;
       border-bottom: 1px solid #ccc;
       padding-top: 10px;
       text-decoration: none;
       text-align: center;
     }

     p {
       font: 200 20px/1.5 Helvetica, Verdana, sans-serif;
       padding-top: 10px;
       margin-right: 10px;
       text-decoration: none;
       text-align: center;
     }

     div {
       margin-left: auto;
       margin-right: auto;
       font: 200 20px/1.5 Helvetica, Verdana, sans-serif;
       padding-top: 10px;
       text-decoration: none;
       text-align: center;
       width: 50%;
     }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>